"""add provisioning audit columns

Revision ID: 14f28221067a
Revises: 6b739f56cf50
Create Date: 2026-04-04 00:56:11.985927

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '14f28221067a'
down_revision: Union[str, None] = '6b739f56cf50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('provisioned_rows', sa.Integer(), nullable=True, comment='Number of rows inserted into target database'))
    op.add_column('jobs', sa.Column('provisioned_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when provisioning completed'))
    op.add_column('jobs', sa.Column('target_ddl', sa.Text(), nullable=True, comment='Generated DDL stored for audit trail'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'target_ddl')
    op.drop_column('jobs', 'provisioned_at')
    op.drop_column('jobs', 'provisioned_rows')
    # ### end Alembic commands ###
