"""Add users table

Revision ID: 43408dc38fa8
Revises: 
Create Date: 2026-04-03 19:42:43.117001

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43408dc38fa8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='User sub claim from Auth.js JWT'),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_key', sa.String(length=1024), nullable=False, comment='S3 object key for the uploaded file'),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'OCR_PROCESSING', 'SCHEMA_PROPOSED', 'AWAITING_REVIEW', 'SCHEMA_LOCKED', 'EXTRACTING', 'MERGING', 'TRANSLATING', 'PROVISIONING', 'COMPLETED', 'FAILED', name='job_status', create_constraint=True), nullable=False),
    sa.Column('output_format', sa.Enum('SQL', 'GRAPH', 'VECTOR', name='output_format', create_constraint=True), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False, comment='Progress percentage 0-100'),
    sa.Column('proposed_schema', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='AI-proposed JSON schema (Phase 1 discovery)'),
    sa.Column('locked_schema', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='User-approved JSON schema (Phase 2 validation)'),
    sa.Column('extracted_data', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Merged extraction result (Phase 3 execution)'),
    sa.Column('output_schema_name', sa.String(length=255), nullable=True, comment='PostgreSQL schema name: job_{uuid}'),
    sa.Column('connection_string', sa.Text(), nullable=True, comment='Connection string delivered to user on completion'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True, comment='Total pages detected by OCR'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
